version: '1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo

  backend:
    build: ./backend
    container_name: cakeshop
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://mashawijesekara:n5AGT6RQWik5U33Z@cluster0.tjxwt5d.mongodb.net/MDCakeShop
      JWT_SECRET: AbholkcnjklHuexw496434178@897

  frontend:
    build: ./frontend
    container_name: cakeshopfront
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - backend
